### ISSUE TITLE
Could you release complete codes for running your work?

### ISSUE THREAD

**Issue by BenoitKAO** [edvinforsgren/ProjSweep#1]
Thank you for your marvelous work!

Could you release complete codes for running your work?

I have received error messages.

---
7.4 M     Trainable params
0         Non-trainable params
7.4 M     Total params
29.471    Total estimated model params size (MB)
Sanity Checking: 0it [00:00, ?it/s]/miniconda3/envs/env1/lib/python3.9/site-packages/pytorch_lightning/utilities/data.py:127: UserWarning: Total length of `DataLoader` across ranks is zero. Please make sure this was your intention.
  rank_zero_warn(
Traceback (most recent call last): 
  File "/data/githubs/ProjSweep/src/run.py", line 25, in <module>
    run_training(save_dir=save_dir, target_path=target_path, input_path=input_path, n_epochs=n_epochs)
  File "/data/githubs/ProjSweep/src/CGAN_train.py", line 250, in run_training
    trainer.fit(model)
  File "/miniconda3/envs/env1/lib/python3.9/site-packages/pytorch_lightning/trainer/trainer.py", line 770, in fit
    self._call_and_handle_interrupt(
  File "/miniconda3/envs/env1/lib/python3.9/site-packages/pytorch_lightning/trainer/trainer.py", line 721, in _call_and_handle_interrupt
    return self.strategy.launcher.launch(trainer_fn, *args, trainer=self, **kwargs)
  File "/miniconda3/envs/env1/lib/python3.9/site-packages/pytorch_lightning/strategies/launchers/spawn.py", line 78, in launch
    mp.spawn(
  File "/miniconda3/envs/env1/lib/python3.9/site-packages/torch/multiprocessing/spawn.py", line 240, in spawn
    return start_processes(fn, args, nprocs, join, daemon, start_method='spawn')
  File "/miniconda3/envs/env1/lib/python3.9/site-packages/torch/multiprocessing/spawn.py", line 198, in start_processes
    while not context.join():
  File "/miniconda3/envs/env1/lib/python3.9/site-packages/torch/multiprocessing/spawn.py", line 160, in join
    raise ProcessRaisedException(msg, error_index, failed_process.pid)
torch.multiprocessing.spawn.ProcessRaisedException":

Process 1 terminated with the following error:
Traceback (most recent call last):
  File "/miniconda3/envs/env1/lib/python3.9/site-packages/torch/multiprocessing/spawn.py", line 69, in _wrap
    fn(i, *args)
  File "/miniconda3/envs/env1/lib/python3.9/site-packages/pytorch_lightning/strategies/launchers/spawn.py", line 101, in _wrapping_function
    results = function(*args, **kwargs)
  File "/miniconda3/envs/env1/lib/python3.9/site-packages/pytorch_lightning/trainer/trainer.py", line 811, in _fit_impl
    results = self._run(model, ckpt_path=self.ckpt_path)
  File "/miniconda3/envs/env1/lib/python3.9/site-packages/pytorch_lightning/trainer/trainer.py", line 1236, in _run
    results = self._run_stage()
  File "/miniconda3/envs/env1/lib/python3.9/site-packages/pytorch_lightning/trainer/trainer.py", line 1323, in _run_stage
    return self._run_train()
  File "/miniconda3/envs/env1/lib/python3.9/site-packages/pytorch_lightning/trainer/trainer.py", line 1353, in _run_train
    self.fit_loop.run()
  File "/miniconda3/envs/env1/lib/python3.9/site-packages/pytorch_lightning/loops/base.py", line 199, in run
    self.on_run_start(*args, **kwargs)
  File "/miniconda3/envs/env1/lib/python3.9/site-packages/pytorch_lightning/loops/fit_loop.py", line 207, in on_run_start
    self.trainer.reset_train_dataloader(self.trainer.lightning_module)
  File "/miniconda3/envs/env1/lib/python3.9/site-packages/pytorch_lightning/trainer/trainer.py", line 1856, in reset_train_dataloader
    self.train_dataloader = self._data_connector._request_dataloader(RunningStage.TRAINING, model=model)
  File "/miniconda3/envs/env1/lib/python3.9/site-packages/pytorch_lightning/trainer/connectors/data_connector.py", line 459, in _request_dataloader
    dataloader = source.dataloader()
  File "/miniconda3/envs/env1/lib/python3.9/site-packages/pytorch_lightning/trainer/connectors/data_connector.py", line 532, in dataloader
    return self.instance.trainer._call_lightning_module_hook(self.name, pl_module=self.instance)
  File "/miniconda3/envs/env1/lib/python3.9/site-packages/pytorch_lightning/trainer/trainer.py", line 1595, in _call_lightning_module_hook
    output = fn(*args, **kwargs)
  File "/data/githubs/ProjSweep/src/CGAN_train.py", line 210, in train_dataloader
    return create_dataloader(self.path_a, self.path_b, batch_size=2, split=0.896, on_gpu=self.on_gpu)
  File "/data/githubs/ProjSweep/src/dataset.py", line 224, in create_dataloader
    loader = DataLoader(dataset, batch_size=batch_size, num_workers=num_workers, shuffle=train, pin_memory=True)
  File "/miniconda3/envs/env1/lib/python3.9/site-packages/torch/utils/data/dataloader.py", line 277, in __init__
    sampler = RandomSampler(dataset, generator=generator)  # type: ignore[arg-type]
  File "/miniconda3/envs/env1/lib/python3.9/site-packages/torch/utils/data/sampler.py", line 97, in __init__
    raise ValueError("num_samples should be a positive integer "
ValueError: num_samples should be a positive integer value, but got num_samples=0

---

Your help is appreciated.

**Comment by BenoitKAO** [comment]
Dear Edvin,

I appreciate your prompt answers in emails.

I am splitting these files into different folders by following your instructions.

Thank you so much.

**Comment by edvinforsgren** [comment]
Perfect, I have now clarified this step in the readme, thank you for highlighting it!

Best, Edvin
