### ISSUE TITLE
After I finished step 4. and ran in 1800 epochs, errors occurred in saving the image.shape. [cv2.error: OpenCV(4.6.0) /io/opencv/modules/imgcodecs/src/loadsave.cpp:737: error: (-215:Assertion failed) image.channels() == 1 || image.channels() == 3 || image.channels() == 4 in function 'imwrite_']

### ISSUE THREAD

**Issue by BenoitKAO** [edvinforsgren/ProjSweep#2]
Dear Edvin,

After I finished step 4. and ran in 1800 epochs, errors occurred in saving the image.shape.

My tracing:
image.shape----> (20, 512, 512)

---
  rank_zero_warn(
Testing DataLoader 0:   0%|                               | 0/1 [00:00<?, ?it/s]  (20, 512, 512)

image.shape----> (20, 512, 512)
Traceback (most recent call last):
  File "/data/githubs/ProjSweep/src/run.py", line 25, in <module>
    run_training(save_dir=save_dir, target_path=target_path, input_path=input_path, n_epochs=n_epochs)
  File "/data/githubs/ProjSweep/src/CGAN_train.py", line 288, in run_training
    trainer.test(model)
  File "/miniconda3/envs/e1/lib/python3.10/site-packages/pytorch_lightning/trainer/trainer.py", line 938, in test
    return self._call_and_handle_interrupt(self._test_impl, model, dataloaders, ckpt_path, verbose, datamodule)
  File "/miniconda3/envs/e1/lib/python3.10/site-packages/pytorch_lightning/trainer/trainer.py", line 721, in _call_and_handle_interrupt
    return self.strategy.launcher.launch(trainer_fn, *args, trainer=self, **kwargs)
  File "/miniconda3/envs/e1/lib/python3.10/site-packages/pytorch_lightning/strategies/launchers/subprocess_script.py", line 93, in launch
    return function(*args, **kwargs)
  File "/miniconda3/envs/e1/lib/python3.10/site-packages/pytorch_lightning/trainer/trainer.py", line 985, in _test_impl
    results = self._run(model, ckpt_path=self.ckpt_path)
  File "/miniconda3/envs/e1/lib/python3.10/site-packages/pytorch_lightning/trainer/trainer.py", line 1236, in _run
    results = self._run_stage()
  File "/miniconda3/envs/e1/lib/python3.10/site-packages/pytorch_lightning/trainer/trainer.py", line 1320, in _run_stage
    return self._run_evaluate()
  File "/miniconda3/envs/e1/lib/python3.10/site-packages/pytorch_lightning/trainer/trainer.py", line 1365, in _run_evaluate
    eval_loop_results = self._evaluation_loop.run()
  File "/miniconda3/envs/e1/lib/python3.10/site-packages/pytorch_lightning/loops/base.py", line 204, in run
    self.advance(*args, **kwargs)
  File "/miniconda3/envs/e1/lib/python3.10/site-packages/pytorch_lightning/loops/dataloader/evaluation_loop.py", line 155, in advance
    dl_outputs = self.epoch_loop.run(self._data_fetcher, dl_max_batches, kwargs)
  File "/miniconda3/envs/e1/lib/python3.10/site-packages/pytorch_lightning/loops/base.py", line 204, in run
    self.advance(*args, **kwargs)
  File "/miniconda3/envs/e1/lib/python3.10/site-packages/pytorch_lightning/loops/epoch/evaluation_epoch_loop.py", line 128, in advance
    output = self._evaluation_step(**kwargs)
  File "/miniconda3/envs/e1/lib/python3.10/site-packages/pytorch_lightning/loops/epoch/evaluation_epoch_loop.py", line 224, in _evaluation_step
    output = self.trainer._call_strategy_hook("test_step", *kwargs.values())
  File "/miniconda3/envs/e1/lib/python3.10/site-packages/pytorch_lightning/trainer/trainer.py", line 1765, in _call_strategy_hook
    output = fn(*args, **kwargs)
  File "/miniconda3/envs/e1/lib/python3.10/site-packages/pytorch_lightning/strategies/ddp.py", line 362, in test_step
    return self.model.test_step(*args, **kwargs)
  File "/data/githubs/ProjSweep/src/CGAN_train.py", line 199, in test_step
    cv2.imwrite(filename, image)
cv2.error: OpenCV(4.6.0) /io/opencv/modules/imgcodecs/src/loadsave.cpp:737: error: (-215:Assertion failed) image.channels() == 1 || image.channels() == 3 || image.channels() == 4 in function 'imwrite_'

Traceback (most recent call last):
  File "/data/githubs/ProjSweep/src/run.py", line 25, in <module>
    run_training(save_dir=save_dir, target_path=target_path, input_path=input_path, n_epochs=n_epochs)
  File "/data/githubs/ProjSweep/src/CGAN_train.py", line 288, in run_training
    trainer.test(model)
  File "/miniconda3/envs/e1/lib/python3.10/site-packages/pytorch_lightning/trainer/trainer.py", line 938, in test
    return self._call_and_handle_interrupt(self._test_impl, model, dataloaders, ckpt_path, verbose, datamodule)
  File "/miniconda3/envs/e1/lib/python3.10/site-packages/pytorch_lightning/trainer/trainer.py", line 723, in _call_and_handle_interrupt
    return trainer_fn(*args, **kwargs)
  File "/miniconda3/envs/e1/lib/python3.10/site-packages/pytorch_lightning/trainer/trainer.py", line 985, in _test_impl
    results = self._run(model, ckpt_path=self.ckpt_path)
  File "/miniconda3/envs/e1/lib/python3.10/site-packages/pytorch_lightning/trainer/trainer.py", line 1236, in _run
    results = self._run_stage()
  File "/miniconda3/envs/e1/lib/python3.10/site-packages/pytorch_lightning/trainer/trainer.py", line 1320, in _run_stage
    return self._run_evaluate()
  File "/miniconda3/envs/e1/lib/python3.10/site-packages/pytorch_lightning/trainer/trainer.py", line 1365, in _run_evaluate
    eval_loop_results = self._evaluation_loop.run()
  File "/miniconda3/envs/e1/lib/python3.10/site-packages/pytorch_lightning/loops/base.py", line 204, in run
    self.advance(*args, **kwargs)
  File "/miniconda3/envs/e1/lib/python3.10/site-packages/pytorch_lightning/loops/dataloader/evaluation_loop.py", line 155, in advance
    dl_outputs = self.epoch_loop.run(self._data_fetcher, dl_max_batches, kwargs)
  File "/miniconda3/envs/e1/lib/python3.10/site-packages/pytorch_lightning/loops/base.py", line 204, in run
    self.advance(*args, **kwargs)
  File "/miniconda3/envs/e1/lib/python3.10/site-packages/pytorch_lightning/loops/epoch/evaluation_epoch_loop.py", line 128, in advance
    output = self._evaluation_step(**kwargs)
  File "/miniconda3/envs/e1/lib/python3.10/site-packages/pytorch_lightning/loops/epoch/evaluation_epoch_loop.py", line 224, in _evaluation_step
    output = self.trainer._call_strategy_hook("test_step", *kwargs.values())
  File "/miniconda3/envs/e1/lib/python3.10/site-packages/pytorch_lightning/trainer/trainer.py", line 1765, in _call_strategy_hook
    output = fn(*args, **kwargs)
  File "/miniconda3/envs/e1/lib/python3.10/site-packages/pytorch_lightning/strategies/ddp.py", line 362, in test_step
    return self.model.test_step(*args, **kwargs)
  File "/data/githubs/ProjSweep/src/CGAN_train.py", line 199, in test_step
    cv2.imwrite(filename, image)
cv2.error: OpenCV(4.6.0) /io/opencv/modules/imgcodecs/src/loadsave.cpp:737: error: (-215:Assertion failed) image.channels() == 1 || image.channels() == 3 || image.channels() == 4 in function 'imwrite_'

Testing DataLoader 0:   0%|          | 0/1 [00:05<?, ?it/s

---

Moreover, there are the same file names, such as 'A1-sumSweepAligned.tif', 'A2-sumSweepAligned.tif', ..., and so on in 17025854 and 17025935 folders downloaded from figshare.com.

How should I split xxx-sumSweepAligned.tif files and save them in the "sumSweepAligned" folder?

I appreciate your help very much.

**Comment by BenoitKAO** [comment]
Thank you very much for your prompt answers.
It works like a charm now.
